# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-16 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0045_merge_20170706_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checksum', models.CharField(db_index=True, max_length=32, unique=True)),
                ('seen', models.BooleanField(default=False, help_text='Has this item been seen by a human?')),
                ('processed', models.BooleanField(default=False, help_text='Has this item had its values validated and adjusted by a human?')),
                ('saved', models.BooleanField(default=True, help_text='Has this item been replicated in the production feed?')),
                ('raw_text', models.TextField(default='')),
                ('ingredient', models.CharField(default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(decimal_places=3, default=1.0, max_digits=9)),
                ('unit_type', models.CharField(blank=True, default='', max_length=127)),
                ('ingredient_type', models.CharField(blank=True, choices=[('mn', 'Main'), ('sc', 'Sauce'), ('gn', 'Garnish'), ('sd', 'Side')], default='mn', max_length=2)),
                ('preparation', models.CharField(blank=True, default='', max_length=255)),
                ('fraction', models.CharField(blank=True, choices=[('1/2', '1/2'), ('1/3', '1/3'), ('2/3', '2/3'), ('1/4', '1/4'), ('3/4', '3/4'), ('1/5', '1/5'), ('2/5', '2/5'), ('3/5', '3/5'), ('4/5', '4/5'), ('1/8', '1/8'), ('3/8', '3/8'), ('5/8', '5/8'), ('7/8', '7/8'), ('N/A', 'N/A')], default='N/A', max_length=4)),
                ('uses_fractions', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checksum', models.CharField(db_index=True, max_length=32, unique=True)),
                ('seen', models.BooleanField(default=False, help_text='Has this item been seen by a human?')),
                ('processed', models.BooleanField(default=False, help_text='Has this item had its values validated and adjusted by a human?')),
                ('saved', models.BooleanField(default=True, help_text='Has this item been replicated in the production feed?')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='', max_length=600)),
                ('prep_time_raw', models.CharField(blank=True, max_length=255)),
                ('prep_time_seconds', models.PositiveIntegerField(default=0)),
                ('cook_time_raw', models.CharField(blank=True, max_length=255)),
                ('cook_time_seconds', models.PositiveIntegerField(default=0)),
                ('servings', models.PositiveIntegerField(default=0)),
                ('difficulty_raw', models.CharField(blank=True, max_length=255)),
                ('difficulty', models.CharField(choices=[('es', 'Easy'), ('md', 'Moderate'), ('dt', 'Difficult')], default='es', max_length=3)),
                ('source_url', models.URLField(blank=True, default='', max_length=600)),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Recipe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ingredientdraft',
            name='recipe_draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.RecipeDraft'),
        ),
        migrations.AddField(
            model_name='ingredientdraft',
            name='recipe_ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.RecipeIngredient'),
        ),
    ]
