# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-16 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0002_auto_20170716_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientdraft',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipedraft',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
