# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-17 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0003_auto_20170716_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipedraft',
            name='description_raw',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='recipedraft',
            name='image_url_raw',
            field=models.URLField(blank=True, default='', max_length=600),
        ),
        migrations.AddField(
            model_name='recipedraft',
            name='name_raw',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipedraft',
            name='servings_raw',
            field=models.CharField(blank=True, default='', max_length=55),
        ),
    ]
