# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-17 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0004_auto_20170717_0609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientdraft',
            old_name='saved',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='recipedraft',
            old_name='saved',
            new_name='published',
        ),
        migrations.AlterField(
            model_name='recipedraft',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=600, unique=True),
        ),
    ]
