# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-02 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20170802_0650'),
        ('data_entry', '0006_auto_20170725_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipedraft',
            name='keywords',
            field=models.ManyToManyField(to='main.Keyword'),
        ),
        migrations.AddField(
            model_name='recipedraft',
            name='tags',
            field=models.ManyToManyField(to='main.Tag'),
        ),
    ]
