# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170629_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metatag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='metatags',
            field=models.ManyToManyField(related_name='posts', to='blog.Metatag'),
        ),
    ]
