# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='firebase_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dish',
            name='firebase_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='firebase_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='blogs',
            field=models.ManyToManyField(to='main.Blog'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='firebase_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
