# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170210_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
