# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170210_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='firebase_id',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
    ]
