# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170210_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='slug',
            field=models.SlugField(help_text='A slug helps query cuisines via url', unique=True),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='slug',
            field=models.SlugField(help_text='A slug helps query highlights via url', max_length=100, unique=True),
        ),
    ]
