# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170211_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=600),
        ),
    ]
