# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170211_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='slug',
            field=models.SlugField(default='', help_text='A slug helps query via url', max_length=255),
            preserve_default=False,
        ),
    ]
