# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20170211_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='profile',
            name='firebase_id',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo_url',
            field=models.URLField(blank=True, default='', max_length=600),
        ),
    ]
