# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20170211_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='firebase_id',
            field=models.CharField(blank=True, default='', max_length=400, unique=True),
        ),
    ]
