# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 17:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_auto_20170211_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='firebase_id',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set([('user', 'firebase_id')]),
        ),
    ]
