# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_deliveryprovider_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
