# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_restaurant_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, help_text='legacy calculated field from Firebase'),
        ),
        migrations.AddField(
            model_name='dish',
            name='views_count',
            field=models.PositiveIntegerField(default=0, help_text='legacy calculated field from Firebase'),
        ),
    ]
