# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 13:25
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20170224_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, db_index=True, default='POINT(0.0 0.0)', srid=4326),
        ),
    ]
