# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20170322_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
