# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_bookingprovder_fulfilmentevent_view'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingProvder',
            new_name='BookingProvider',
        ),
    ]
