# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20170326_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='random',
            field=models.BigIntegerField(default=main.models.random_number),
        ),
        migrations.AlterField(
            model_name='bookingprovider',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bookingprovider',
            name='logo_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterUniqueTogether(
            name='openingtime',
            unique_together=set([('restaurant', 'opens', 'closes', 'day_of_week', 'valid_from', 'valid_through')]),
        ),
    ]
