# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20170413_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
