# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20170508_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit_type',
            field=models.CharField(blank=True, default='', max_length=127),
        ),
    ]
