# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20170508_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cook_time_seconds',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('ESY', 'Easy'), ('MOD', 'Moderate'), ('DFT', 'Difficult')], default='ESY', max_length=3),
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time_seconds',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='ingredient_type',
            field=models.CharField(blank=True, default='', max_length=127),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together=set([('recipe', 'ingredient', 'ingredient_type')]),
        ),
    ]
