# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 07:36
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0031_auto_20170525_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', django.contrib.gis.db.models.fields.PointField(db_index=True, default='POINT(0.0 0.0)', srid=4326)),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('max_distance_meters', models.PositiveIntegerField(null=True)),
                ('result_size', models.PositiveIntegerField(default=0)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('has_delivery', models.BooleanField(default=False)),
                ('has_booking', models.BooleanField(default=False)),
                ('suburb', models.CharField(default='', max_length=255)),
                ('page', models.PositiveIntegerField(default=1)),
                ('cuisines', models.ManyToManyField(to='main.Cuisine')),
                ('highlights', models.ManyToManyField(to='main.Highlight')),
                ('keywords', models.ManyToManyField(to='main.Keyword')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_queries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
