# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_dishquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishquery',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
