# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20170522_0841'),
        ('main', '0033_dishquery_created'),
    ]

    operations = [
    ]
