# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_merge_20170526_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
