# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20170526_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishquery',
            name='tags',
            field=models.ManyToManyField(to='main.Tag'),
        ),
    ]
