# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-28 12:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0036_dishquery_tags'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('user', 'dish')]),
        ),
    ]
