# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20170528_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishquery',
            name='query_string',
            field=models.TextField(default=''),
        ),
    ]
