# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_dishquery_query_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=600),
        ),
    ]
