# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_recipe_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='keywords',
            field=models.ManyToManyField(to='main.Keyword'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='main.Tag'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_time_seconds',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
