# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 17:21
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0041_auto_20170616_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', django.contrib.gis.db.models.fields.PointField(default='POINT(0.0 0.0)', srid=4326)),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('result_size', models.PositiveIntegerField(default=0)),
                ('min_total_time', models.PositiveIntegerField(default=0, null=True)),
                ('max_total_time', models.PositiveIntegerField(default=0, null=True)),
                ('difficulty', models.CharField(default='', max_length=5)),
                ('page', models.PositiveIntegerField(default=1)),
                ('query_string', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('keywords', models.ManyToManyField(to='main.Keyword')),
                ('tags', models.ManyToManyField(to='main.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_queries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook_time_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='main.Keyword'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.Tag'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='total_time_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
