# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 07:21
from __future__ import unicode_literals

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20170616_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, default=''),
        ),
    ]
