# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_restaurant_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='fraction',
            field=models.CharField(blank=True, choices=[('1/2', '1/2'), ('1/3', '1/3'), ('2/3', '2/3'), ('1/4', '1/4'), ('3/4', '3/4'), ('1/5', '1/5'), ('2/5', '2/5'), ('3/5', '3/5'), ('4/5', '4/5'), ('1/8', '1/8'), ('3/8', '3/8'), ('5/8', '5/8'), ('7/8', '7/8'), ('N/A', 'N/A')], default='N/A', max_length=4),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='preparation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='uses_fractions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=9),
        ),
    ]
