# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_restaurant_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingtime',
            name='closes',
            field=models.TimeField(help_text='24 hrs, e.g. 17:00 is 5pm'),
        ),
        migrations.AlterField(
            model_name='openingtime',
            name='opens',
            field=models.TimeField(help_text='24 hrs, e.g. 17:00 is 5pm'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='blogs',
            field=models.ManyToManyField(related_name='restaurant', to='main.Blog'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
        ),
    ]
