# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-06 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20170704_0422'),
        ('main', '0044_auto_20170629_1349'),
    ]

    operations = [
    ]
