# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_merge_20170706_0855'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together=set([]),
        ),
    ]
