# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-27 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20170725_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age_max',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='age_min',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=55),
        ),
    ]
