# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-02 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_auto_20170727_0504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name_plural': 'Dishes'},
        ),
        migrations.AlterModelOptions(
            name='dishquery',
            options={'verbose_name_plural': 'Dish Queries'},
        ),
        migrations.AlterModelOptions(
            name='recipequery',
            options={'verbose_name_plural': 'Recipe Queries'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='age_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
