# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20170806_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=600, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together=set([('name', 'description')]),
        ),
    ]
